// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdAc2jxmz9vQLiXRSnPgNrw0DXQ0A-MD4',
    appId: '1:427268826262:web:76c1ea356f40636e3d4eb7',
    messagingSenderId: '427268826262',
    projectId: 'mallfeedback',
    authDomain: 'mallfeedback.firebaseapp.com',
    storageBucket: 'mallfeedback.appspot.com',
    measurementId: 'G-6DSYRX0FVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ8ksI6oc9DrbUCHW07dm2DK5hMurPELc',
    appId: '1:427268826262:android:99a5a7d4de14d5b93d4eb7',
    messagingSenderId: '427268826262',
    projectId: 'mallfeedback',
    storageBucket: 'mallfeedback.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8US95fAWOL6r_H5ZaNhRtc078UOGqq04',
    appId: '1:427268826262:ios:b72a2ccdc344d8d83d4eb7',
    messagingSenderId: '427268826262',
    projectId: 'mallfeedback',
    storageBucket: 'mallfeedback.appspot.com',
    iosBundleId: 'com.example.mallApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8US95fAWOL6r_H5ZaNhRtc078UOGqq04',
    appId: '1:427268826262:ios:b72a2ccdc344d8d83d4eb7',
    messagingSenderId: '427268826262',
    projectId: 'mallfeedback',
    storageBucket: 'mallfeedback.appspot.com',
    iosBundleId: 'com.example.mallApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdAc2jxmz9vQLiXRSnPgNrw0DXQ0A-MD4',
    appId: '1:427268826262:web:c5a09130fc875e463d4eb7',
    messagingSenderId: '427268826262',
    projectId: 'mallfeedback',
    authDomain: 'mallfeedback.firebaseapp.com',
    storageBucket: 'mallfeedback.appspot.com',
    measurementId: 'G-4BF58VX3Y4',
  );
}
